### ISSUE TITLE
[BUG] v2.0.5 breaks Package Manager, User Manager, and Backup panes

### ISSUE THREAD

**Issue by UgmaDevelopment** [eXist-db/dashboard#121]
**Describe the bug**
Dashboard v2.0.5 appears to be broken. The Package Manager, User Manager, and Backup panes don't appear correctly or at all when navigated to.

**Expected behavior**
I expected the panes to appear just like they do in v2.0.4.

**To Reproduce**
I ran into the problem when I upgraded my dashboard from v2.0.4 to v2.0.5. I did this originally via the orange updates bar in the package manager.

**Unit Test**
Sorry, I don't know enough about unit testing to provide a useful unit test, but here's a script that should install v2.0.5:

```XQuery
xquery version "3.1";
repo:undeploy("http://exist-db.org/apps/dashboard"), 
repo:remove("http://exist-db.org/apps/dashboard"),
repo:install-and-deploy("http://exist-db.org/apps/dashboard", "2.0.5", "http://demo.exist-db.org/exist/apps/public-repo/modules/find.xql")
```
_**For those stuck in v2.0.5, you can run this same script to downgrade to v2.0.4 by simply changing the version number in the script.**_

**Integration Test**
This may or may not be helpful
```javascript
describe('The app', function() {
  it('should load', function() {
    // Go to each broken page
    cy.visit('http://localhost:8080/exist/apps/dashboard/admin#/packagemanager')
    cy.visit('http://localhost:8080/exist/apps/dashboard/admin#/usermanager')
    cy.visit('http://localhost:8080/exist/apps/dashboard/admin#/backup')
  })
```

The exact steps you took when you encountered the problem:
1. Install v2.0.5 of the dashboard
2. Login as admin
3. Navigate to the Package Manager, User Manager, and Backup panes

**Screenshots**
### _**Windows 7: Firefox 72.0.1**_
**Launcher**—appears just fine
![image](https://user-images.githubusercontent.com/19827042/72369383-35598700-36bd-11ea-87f0-02ac9b749ba5.png)

Console output: 
![image](https://user-images.githubusercontent.com/19827042/72368885-245c4600-36bc-11ea-8556-be3c92968fcb.png)

----------------------------------------------------------------------

**Package Manager**—This one partially appears, but no packages appear in either "Installed" or "Available"
![image](https://user-images.githubusercontent.com/19827042/72366144-edcffc80-36b6-11ea-95e0-5e12f2ba8770.png)
Console output: 
![image](https://user-images.githubusercontent.com/19827042/72368980-5b325c00-36bc-11ea-94df-a141b39e06ae.png)

----------------------------------------------------------------------

**User Manager** 
![image](https://user-images.githubusercontent.com/19827042/72366097-d42eb500-36b6-11ea-829f-7fd3169e93df.png)
Console output: 
![image](https://user-images.githubusercontent.com/19827042/72369032-7a30ee00-36bc-11ea-9a3e-8602ae149961.png)

----------------------------------------------------------------------

**Backup**
![image](https://user-images.githubusercontent.com/19827042/72366316-3edff080-36b7-11ea-8a6f-ffe358bef599.png)
Console output: 
![image](https://user-images.githubusercontent.com/19827042/72369071-8fa61800-36bc-11ea-9a21-628d6da6e02e.png)

### _**Windows 7: Chrome 79.0.3945.117**_
so broken that nothing displays
Lots of `Polymer is not defined`
[Console output](https://gist.github.com/UgmaDevelopment/87a15650a647d8b2dd389bd7f088e4d9)

**Context (please always complete the following information):**
 - OS: Client: Windows 7; Server: Windows Server 2016 10.0 amd64
 - eXist-db Version: v5.1.1
 - Java Version: 1.8.0_141
-  App Version: 2.0.5
- Browser: 
    - Firefox 72.0.1: shows dashboard and some panes
    - Chrome 79.0.3945.117: shows no dashboard, and no panes

**Additional context**
- How is eXist-db installed? Jar Installer
- Any custom changes in e.g. `conf.xml`? A single unrelated scheduler job.

**Comment by UgmaDevelopment** [comment]
When I go to the dashboard, or any of the pane's URI's directly from localhost while using the server (Windows Server 2016 10.0, not Windows 7), using Firefox 72.01, which is the same Firefox version as Windows 7, I get a blank screen and bunch of `Polymer is not defined`, like I did on Chrome.
![image](https://user-images.githubusercontent.com/19827042/72370305-325f9600-36bf-11ea-9ae5-5eb7c72f44fb.png)

**Comment by wolfgangmm** [comment]
I noticed the same issue a few minutes ago. Looks like the package uploaded to the eXist public repo was  damaged or incomplete. I rebuilt and replaced it. This should fix the issue.  To reinstall the dashboard, run the following query from e.g. eXide:

```xquery
repo:remove("http://exist-db.org/apps/dashboard"),
repo:install-and-deploy("http://exist-db.org/apps/dashboard", "http://exist-db.org/exist/apps/public-repo/find")
```

**Comment by joewiz** [comment]
@wolfgangmm The new version of dashboard has a different hash, which led maven to throw an error when fetching xars from the public repo:

> [ERROR] Failed to execute goal org.exist-db.maven.plugins:public-xar-repo-plugin:1.2.0:resolve (fetch-xars) on project exist-distribution: Downloaded file does not match PackageInfo checksum: expected=eee57e94f591ca86d12ad4aa14933bfe0f33af2c23a55a5bc5532a299e2764ad, actual=403b6925c14d0a951950ffd1d87a17ac15f7f1d5210b0acc278b639e43ff8f15 -> [Help 1]

I've gone and updated the public-repo apps.xml file with the correct hash, which in future can be calculated with:

```xquery
xquery version "3.1";

import module namespace crypto = "http://expath.org/ns/crypto";

crypto:hash(
    util:binary-doc("/db/apps/public-repo/public/dashboard-2.0.5.xar"),
    "sha256",
    "hex"
)
```

**Comment by adamretter** [comment]
@joewiz when you upload a new XAR the public-repo app calculates the checksum automatically. I don't understand how these could be out of sync?

**Comment by joewiz** [comment]
@adamretter It can happen if you upload directly to the collection rather than publishing via the app. The latter involves a lot of waiting for the xars to all be unzipped, metadata regenerated, etc.

**Comment by adamretter** [comment]
@joewiz ah ha! So the latter is slower, but the former is open to human error ;-)

**Comment by line-o** [comment]
I just upgraded to v2.0.5 without any problems. Therefore, closing this issue.
