### ISSUE TITLE
[BUG] Logging in shouldn't require duplicate entry of credentials

### ISSUE THREAD

**Issue by joewiz** [eXist-db/dashboard#156]
Almost every time I open dashboard and try to log in to a dba-only resource, I have to authenticate twice, via these dialogs:

> <img width="315" alt="Screen Shot 2020-11-29 at 9 04 17 PM" src="https://user-images.githubusercontent.com/59118/100561324-9c0c7280-3286-11eb-8e5a-048375d9662a.png">

> <img width="366" alt="Screen Shot 2020-11-29 at 9 05 14 PM" src="https://user-images.githubusercontent.com/59118/100561330-a2025380-3286-11eb-8c44-3b9633266474.png">

In addition, when tabbing out of the password field in the dialog shown in the 1st screenshot above, the focus should be on the Submit button, so that the form can be submitted via spacebar.

**Comment by adamretter** [comment]
@joewiz I can confirm that I have seen the same problem for longer than I can remember. I always assumed the issue was something with my browser as no-one else seemed to have mentioned it. Thanks for confirming it's not just me!

**Comment by JoernT** [comment]
hm, would have liked to look into that. However i cannot reproduce that and also haven't experienced that before (which makes it kind of hard to fix it ;)

Could you guys give more details like OS, Browser (Version) etc. ?

**Comment by adamretter** [comment]
I am using latest Chrome on macOS 11.2.3.

**Comment by JoernT** [comment]
same here - hm, any plugins?

**Comment by adamretter** [comment]
@JoernT Nope.

**Comment by JoernT** [comment]
that's crazy - seems we have exact same configurations in respect to that and i never experienced this issue.

**Comment by adamretter** [comment]
@joewiz You also reported this. Perhaps you could share the details of your setup?

**Comment by plutonik-a** [comment]
Hi @JoernT 
I experience the same behavior and would like to provide info on my setup:
* eXist Version : 5.1.1
* Dashboard 2.0.6

I have openend the developer tools and tracked the network when requesting http://localhost:8080/exist/apps/dashboard/index.html and submitting the login overlay, and observed the console logs.

This is was happens:
1. The first stack of calls prompted in the network tab:
<img width="755" alt="Screenshot 2021-03-24 at 17 37 23" src="https://user-images.githubusercontent.com/1157669/112349443-03807f00-8cc9-11eb-9900-8e400a4aa4f2.png">
2. Then I get redirected again to the login page with the embedded login dialog - this shows the stack trace of the second login:
<img width="745" alt="Screenshot 2021-03-24 at 17 37 41" src="https://user-images.githubusercontent.com/1157669/112349478-0d09e700-8cc9-11eb-9de3-eafc9342b134.png">
3. The console also shows the ajax calls is called twice:  
<img width="1258" alt="Screenshot 2021-03-24 at 17 35 00" src="https://user-images.githubusercontent.com/1157669/112349913-6d008d80-8cc9-11eb-9b6e-801f0d80e165.png">
