### ISSUE TITLE
Can we delete `develop` branch?

### ISSUE THREAD

**Issue by joewiz** [eXist-db/dashboard#54]
The last commit in the `develop` branch is from 2013. If development isn't happening in the `develop` branch but in the `master` branch, let's delete `develop`.

**Comment by JoernT** [comment]
i support this. This dashboard is about to be deprecated once the new one is ready. It's already on the way but will still take me some time to finish up. I don't think we should do further development on dashboard aside from hotfixes probably.

**Comment by joewiz** [comment]
Thanks for everyone's feedback. I've now deleted the develop branch.
