### ISSUE TITLE
Remove webstart link from dashboard

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/dashboard#66]
See https://github.com/eXist-db/exist/issues/1923 

will be replaced by a XAR file. rationale: simplification of build scripts, no JAR signing conflicts etc.

needs to be done before release of v5.0RC or can it be later ? @adamretter 

<img width="805" alt="image" src="https://user-images.githubusercontent.com/1700062/41153260-84c82982-6b16-11e8-8aad-fb44a2a0cb4e.png">

**Comment by joewiz** [comment]
@dizzzz @adamretter Could you update us on the status of this? Are you proposing this be included in dashboard 2.0? How does it relate to https://github.com/Trundler/existdb-webstart?

**Comment by dizzzz** [comment]
I'd still like the idea to have the webstart stuff isolated from the exist-db core. This makes building quite more simpler. To me, having it part of eXistdb v5.x makes most sense.

The migration to Maven would be more simple too.

**Comment by joewiz** [comment]
Ok! Is this still a dashboard issue?

**Comment by dizzzz** [comment]
This ticket, yes.

**Comment by JoernT** [comment]
can't remember to have ever seen that in new dashboard

**Comment by line-o** [comment]
@dizzzz can this issue be closed?

**Comment by dizzzz** [comment]
it can be removed. post Java8 webstart is dead. It is not functional anymore, except Oxygen used the old interface for retrieving dependencies; In the teleconference we discussed the possibility to migrate to another API, VScode, Atom editor or the one maintained by @adamretter's evolved binary.
