### ISSUE TITLE
App installation woes

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/dashboard#67]
Tested on exist-db `4.2.0` and `5.0.0-SNAPSHOT-e867da955` with Dashboard  `1.1.0` and both in FF and Safari
Launching apps from dashboard no longer works as expected. 

To reproduce on a clean installation, install e.g. the documentation or new package manger (any app will do) apps. then try to go to the app by clicking on it's icon either on dashboard or from inside package-manager.

Apps installed:
*   from manually uploading .xars (via package manger old or new) work as expected
*   via auto-deploy folder also work as expected
*   from public-repo result in the following:

```
<exist:result xmlns:exist="http://exist.sourceforge.net/NS/exist">
<exist:collection name="/db/apps/packagemanager" created="2018-06-08T10:42:47.41Z" owner="admin" group="dba" permissions="rwxrwxr-x">
<exist:resource name="login.html" created="2018-06-08T10:42:47.415Z" last-modified="2018-06-08T10:42:47.415Z" owner="admin" group="dba" permissions="rwxrwxr-x"/>
<exist:resource name="configuration.xml" created="2018-06-08T10:42:47.463Z" last-modified="2018-06-08T10:42:47.463Z" owner="admin" group="dba" permissions="rwxrwxr-x"/>
</exist:collection>
</exist:result>
```
 If I check the contents of the apps collection in `/db/apps/xxx` it appears empty. 

Force reloading seems to resolve the issue. 

It shouldn't matter how an application was installed, and users should not have to force-reload when navigating from the dashboard to individual apps, thats what it is there for after all.

**Comment by joewiz** [comment]
Confirmed, I am seeing app installation fail when installing from the public repo with dashboard-1.1.0 and shared-resources-0.6.0. My apologies for not testing thoroughly enough before yesterday's updates to these apps. I will need to investigate the cause and then will aim to release an emergency hotfix ASAP.

**Comment by joewiz** [comment]
As discussed in HipChat, the problem described here is a symptom of an NPE in the eXist core, not a problem in dashboard. This issue is being tracked at https://github.com/eXist-db/exist/issues/1928.
