### ISSUE TITLE
Backup-central does not sort entries

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/dashboard#7]
Despite the sorting 'items' on top of the table, clicking on these 'items' the table is not sorted. the table is refreshed.

In  one exist-db instance the list of backup files is kept more or less randomly, at an other instance the alpha-order is not changeable.

Browsers: FireFox , Safari and Chrome

**Comment by joewiz** [comment]
@dizzzz I assume this is fixed in dashboard 2.x, but if not please open a new issue referencing the version tested.
