### ISSUE TITLE
dashboard relies on deprecated xmldb function in login module

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/dashboard#83]
results no dashboard:
![Screenshot 2019-04-03 at 17 42 56](https://user-images.githubusercontent.com/6205362/55493340-09db4380-5639-11e9-95ab-adf1112654c3.png)

the relevant passage from the log:

```
javax.servlet.ServletException: An error occurred while processing request to /exist/apps/dashboard/: err:XPST0017 error found while loading module login: Error while loading module resource:org/exist/xquery/modules/persistentlogin/login.xql: Function xmldb:is-admin-user()  is not defined in module namespace: http://exist-db.org/xquery/xmldb [at line 78, column 24]
```

**Comment by joewiz** [comment]
Which version of Dashboard?

**Comment by duncdrum** [comment]
good question, the one that is included in the autobuild when checking out the main repo today.

**Comment by joewiz** [comment]
Which branch of the main repo?

**Comment by duncdrum** [comment]
`develop`

**Comment by duncdrum** [comment]
and here is a [test run](https://travis-ci.com/eXist-db/e2e-core/builds/107007788) reproducing the behaviour. Comparing `4.x` to `5.x` this seems to affect `dashboard-2.0`, and all apps that rely on the same login code. In `dashboard-1.x` has problems with collection browser (could be a timeout problem, but i doubt it)

**Comment by craigberry** [comment]
As I mentioned on exist-open, it looks like this commit:

<https://github.com/eXist-db/exist/commit/24134f99fe99e137a6067a3613e6bdd6779904a5>

got rid of at least one function that is still in use by at least one of eXist's own built-in modules.  The attached patch fixes that particular problem, but there seem to be other issues with the dashboard.  Launcher, Package Manager, and User Manager are still non-functional.  I don't have any further insight about what's going on there.

[0001-Use-is-dba-rather-than-deprecated-is-admin-user-in-l.patch.zip](https://github.com/eXist-db/dashboard/files/3044770/0001-Use-is-dba-rather-than-deprecated-is-admin-user-in-l.patch.zip)

**Comment by joewiz** [comment]
Fixed by https://github.com/eXist-db/exist/commit/2a81a107db9e30d253f48da4b366980c2fdef567.
