### ISSUE TITLE
Login to dashboard fails if not in "dba" group

### ISSUE THREAD

**Issue by reinhapa** [eXist-db/dashboard#90]
It's not possible to login into the dashboard using a user not in the group `dba` in contrast using the Java client, where this is possible.

**Comment by duncdrum** [comment]
@reinhapa is which version of Dashboard and exist do you experience this with? Are there any errors in the logs or on screen?

**Comment by reinhapa** [comment]
@duncdrum using the latest `develop` and got no error message. I just get the login form re-shown.

**Comment by JoernT** [comment]
Hi Patrick,

this is by intend as dashboard gives access to packagemanager, usermanager,
backup etc. which usually should be available to admins only. However if
there a valid use cases this certainly can be discussed.

Joern

**Comment by reinhapa** [comment]
@JoernT the intention does just not reveal to a user in that way.

1. If the login fails due to a wrong user id or password there should be an according error message to be shown
2. Why not only show those actions that can be used (Launcher, Settings and Logout) after successful login.
3. I would suggest to have to new groups `backup` and `package` in order to enable the specific "Backup" and "Package Manager" functions.

Within the the Launcher all Monex should then also only if the user has the appropriate `monex` group.

**Comment by adamretter** [comment]
So one of my customers just experienced this as quite a shock when upgrading to 5.0.0. As this is quite different behaviour from 4.x.x. As their users could not log in, they assumed that the system was broken. This is a bad first impression, and must be fixed.

**Comment by wolfgangmm** [comment]
I fixed this in 2 minutes by changing two lines in the controller, but we also need to hide those tabs which don't make sense for non-dba user. I'll send a PR with this next days. 

The XQuery modules which do the actual work are largely the same between the old and new dashboard, which is good because I recognize the code written by myself and other core team members ;-)
